# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f98110343fe1a1d7b75db61b1abe44d74241a609d1c407864a4d033d0fc3707d90300da1b0d61b4fc2199a9561023081aa5c9bf99af9b6e92a10904b48e74fe

test:
  secret_key_base: 45272f9d56ae3ac64a28634768cda799c38f2e963841ba860e5bf35b2708f8dca944be7fcbbeea88e50dd24271d4ee54ac9e615b8cf197f3575836453eb16126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
